"""Keep these in lockstep with src/lib/constants.ts. Do not change fee or status rules here."""

PLATFORM_FEE_LYD = 5
CITY = "Benghazi"
TIMEZONE = "Africa/Tripoli"
SLOT_STEP_MIN = 30
BOOKING_REQUEST_TIMEOUT_MINUTES = 30
DAY_BUCKET = "DAY"
DEFAULT_DAILY_CAPACITY = 4
DEFAULT_HAIR_CAPACITY = 5

BLOCKING_STATUSES = ("PENDING", "CONFIRMED", "CHECKED_IN", "IN_PROGRESS")
LIVE_BOOKING_STATUSES = ("PENDING", "CONFIRMED", "CHECKED_IN", "IN_PROGRESS")
PASS_HIDDEN_STATUSES = ("PENDING", "DECLINED", "EXPIRED")

SESSION_COOKIE = "bridey_session"
ADMIN_COOKIE = "bridey_admin"
SESSION_DAYS = 30
ADMIN_SESSION_DAYS = 7
